### ISSUE TITLE
Api for uploading a build.

### ISSUE THREAD

**Issue by aiKrice** [Linkvalue/Appbuild#59]
Need to be authenticated.
Need to be attached to an existing app
Need a response for success of failure
Need a multipart format POST with this data: 

POST /application/3/build
header auth
file: binary
{"comment": "some comments",
"version": "version"}
only admin token should upload a build
header, file, version must be mandatory, comment optionnal

response: 
HTTP1.1 status_code
{"error": "reason",}
if success, entity response
{"buildId": id, ...}

**Comment by thomasleduc** [comment]
To resume : 

## Upload a build on the application

### Request

```
POST /api/application/{application_id}/build
```

### Response

```json
  {
    "id": 1,
    "label": "Test application iOS [1.5.2]",
    "version": "1.5.2",
    "comment": "This is a comment for this build.\nWith a line break.\nAnd another one.\n",
    "is_latest": true,
    "download_link": "http://app-build.dev/app_dev.php/fr/application/3/build/3/download",
    "application": {
      "id": 3
    }
  }
```

Questions :
- Is it the right file to update ? `Majora\OTAStore\ApplicationBundle\Controller\Api\BuildController.php`
- What is the maximum size of a build ?
- If the app doesn't exist, should we create it or return a 404 ?

**Comment by aiKrice** [comment]
For the download_link, it can't be an url but must be the binary file. like this

{
    "id": 1,
    "label": "Test application iOS [1.5.2]",
    "version": "1.5.2",
    "comment": "This is a comment for this build.\nWith a line break.\nAnd another one.\n",
    "is_latest": true,
    "application": {
      "id": 3
    }
  }

-------------------------------------------------------
file: hsdgcozdvozvo

cf multipart enctype?

**Comment by Oliboy50** [comment]
Please read this before choosing how to implement a solution: https://philsturgeon.uk/api/2016/01/04/http-rest-api-file-uploads/

> Why Multipart Mostly Sucks

I personnaly like the "double requests" option, like Youtube API does:

- first request:

```
PUT /application/3/build HTTP/1.1
header auth
Content-Type: application/json
X-Upload-Content-Length: 3000000
X-Upload-Content-Type: video/*

{
    "comment": "some comments",
    "version": "version"
}
```

=> response:

```
HTTP/1.1 200 OK
Location: http://domain.com/application/3/build/file
```

- second request:

```
PUT http://domain.com/application/3/build/file HTTP/1.1
header auth
Content-Length: CONTENT_LENGTH
Content-Type: CONTENT_TYPE

BINARY_FILE_DATA
```

=> response:

```
HTTP/1.1 200 OK
```

**Comment by aiKrice** [comment]
Non, la spec prevoir ca en 1 seul requete: https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2
C'est la merde a coder sinon et ca cree de la complexite pour rien.
j'ai deja mis le format demandé, svp, ne le changez pas.

**Comment by Oliboy50** [comment]
@SaezChristopher si on doit faire du multipart, je n'vois pas pourquoi on s'embête avec l'API.
La requête qui permet d'upload actuellement depuis le BO est déjà une requête multipart.
Est-ce qu'on pourrait avoir un peu de contexte stp => quel est le besoin derrière l'upload d'un fichier via l'API ?

**Comment by thomasleduc** [comment]
The @SaezChristopher needs is to automate build upload through bash script for example. As I've understand, it looks like he's ready to make 2 curls, as long as we are able to provide the associate bash script that keeps the id between the 2 calls.
